spring:
  r2dbc:
    url: ${POSTGRES_URI}
    username: root
    password: root
logging:
  level:
    org:
      springframework:
          r2dbc: DEBUG
server:
  error:
    include-stacktrace: on_param
